server:
  port: 8081
spring:
  application:
    name: livehouse-ticket
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/livehouse_ticket?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: localhost
    # 消息通信端口 安装完rabbitMQ后有个自带的前端可视化管理UI页面，端口15672，浏览器访问
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 生产者配置
    publisher-confirms: true
    publisher-returns: true
    # 消费者配置
    listener:
      simple:
        # Spring AMQP 框架自动ack/nack ->  消费者方法正常执行结束→自动 ack，方法抛异常→自动 nack
        # 方法正常返回 → 框架 basicAck(deliveryTag, false) → broker 删消息
        # 方法抛异常   → 框架 basicNack(deliveryTag, defaultRequeueRejected) → broker 按 requeue 决定去向
        acknowledge-mode: auto
        # 初始消费者线程数量 ——>  RabbitMQ 的队列模型保证： 一条消息只会投递给一个消费者 。`concurrency: 5` 的含义是容器创建 5 个消费者线程，它们各自从队列里抢不同的消息并行处理——5 条不同消息同时被 5 个线程处理，而不是 1 条消息被 5 个线程抢着处理。
        concurrency: 5
        # 动态扩容的最大数量
        max-concurrency: 10
        # 重试机制及次数
        retry:
          enabled: true
          max-attempts: 3
        # 设置broker（RabbitMQ）默认消息投递规则： false代表消费失败(nack)不重新投递消息入队
        default-requeue-rejected: false
        prefetch: 10
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.livehouse.entity # 别名扫描包
logging:
  level:
    com.livehouse: debug

livehouse:
  upload:
    dir: frontend-livehouse/uploads
    url-prefix: /uploads/
